### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by puntogil** [jsendnsca/jsendnsca#25]
Hi
When I try to run tests I get this error:

Running com.googlecode.jsendnsca.NagiosPassiveCheckSenderTest
Exception in thread "MultiServerThread" java.lang.IllegalArgumentException: LevelValue [-14207] is not a valid level
        at com.googlecode.jsendnsca.Level.toLevel(Level.java:69)
        at com.googlecode.jsendnsca.builders.MessagePayloadBuilder.withLevel(MessagePayloadBuilder.java:93)
        at com.googlecode.jsendnsca.mocks.NagiosNscaStub$MultiServerThread.parsePayload(NagiosNscaStub.java:208)
        at com.googlecode.jsendnsca.mocks.NagiosNscaStub$MultiServerThread.run(NagiosNscaStub.java:161)
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.688 sec - in com.googlecode.jsendnsca.NagiosPassiveCheckSenderTest

Any idea why? or how to fix it?
Environment:
Apache Maven 3.3.3 (NON-CANONICAL_2015-07-10T12:37:52_mockbuild; 2015-07-10T14:37:52+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-1.b03.fc23.i386/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.4.6-300.fc23.i686", arch: "i386", family: "unix"
Thanks in advance

**Comment by rajneeshpatel** [comment]
OK, this was down to a test which

* which wasn't really asserting anything
* sending a message using Triple DES which is not supported by the test stub hence the exception/stacktrace.

As a result to avoid any confusion in future and remove any doubt that Triple DES is being tested, removed the test.
